language: cpp
compiler:
  - gcc
before_install:
  - travis_retry sudo add-apt-repository -y ppa:named-data/ppa
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq ndnx-dev
  - travis_retry sudo apt-get install -qq libboost1.48-all-dev libcrypto++-dev libsqlite3-dev
install:
  - travis_retry git clone --depth 1 git://github.com/named-data/ndn-cxx ndn-cxx
  - cd ndn-cxx
  - ./waf configure
  - ./waf -j1
  - sudo ./waf install
  - cd ..
script:
  - ./waf configure
  - ./waf -j1
  - sudo ./waf install
