language: cpp
compiler:
  - clang
  - gcc
before_install:
  - travis_retry sudo add-apt-repository -y ppa:named-data/ppa
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq autotools-dev
  - travis_retry sudo apt-get install -qq ndnx-dev
  - travis_retry sudo apt-get install -qq libboost-all-dev
  - travis_retry sudo apt-get install -qq libcrypto++-dev
  - travis_retry sudo apt-get install -qq libsqlite3-dev
install:
  - travis_retry git clone git://github.com/cawka/ndn-cpp ndn-cpp
  - cd ndn-cpp
  - autoreconf -f --install
  - ./configure --without-c++11 --with-system-boost
  - make
  - sudo make install
  - cd .. 
script:
  - ./waf configure
  - ./waf -j1
